import card1 from "./assets/imges/card_1.png";
import card2 from "./assets/imges/card_2.png";
import card3 from "./assets/imges/card_3.png";
import card4 from "./assets/imges/card_4.png";
import card5 from "./assets/imges/card_5.jpg";
import card6 from "./assets/imges/card_6.jpg";
import card8 from "./assets/imges/card_8.jpg";
const cardData = {
  data: [
    {
      img: card1,
      title: "Смартфон Samsung G",
      price: "7 300 000 сум ",
      price2: "от 2 435 000 сум ",
      gift: true,
      discount: true,
      trade: false,
      id: 1,
    },
    {
      img: card2,
      title: "Смартфон Apple iphon",
      price: "7 300 000 сум ",
      price2: "от 2 435 000 сум ",
      gift: false,
      discount: false,
      trade: true,
      id: 2,
    },
    {
      img: card3,
      title: "Наушники Apple Airpo",
      price: "7 300 000 сум ",
      price2: "от 2 435 000 сум ",
      gift: false,
      discount: false,
      trade: true,
      id: 3,
    },
    {
      img: card4,
      title: "Samsung Galaxy Z Fold",
      price: "7 300 000 сум ",
      price2: "от 2 435 000 сум ",
      gift: true,
      discount: true,
      trade: false,
      id: 4,
    },
    {
      img: card5,
      title: "Смартфон Apple iphon",
      price: "7 300 000 сум ",
      price2: "от 2 435 000 сум ",
      gift: false,
      discount: false,
      trade: true,
      id: 5,
    },
    {
      img: card6,
      title: "Смартфон Samsung G",
      price: "7 300 000 сум ",
      price2: "от 2 435 000 сум ",
      gift: true,
      discount: true,
      trade: false,
      id: 6,
    },
    {
      img: card3,
      title: "Смартфон Apple iphon",
      price: "7 300 000 сум ",
      price2: "от 2 435 000 сум ",
      gift: false,
      discount: false,
      trade: true,
      id: 7,
    },
    {
      img: card8,
      title: "Наушники Apple Airpo",
      price: "7 300 000 сум ",
      price2: "от 2 435 000 сум ",
      gift: false,
      discount: false,
      trade: true,
      id: 8,
    },
    {
      img: card4,
      title: "Samsung Galaxy Z Fold",
      price: "7 300 000 сум ",
      price2: "от 2 435 000 сум ",
      gift: true,
      discount: true,
      trade: false,
      id: 9,
    },
    {
      img: card2,
      title: "Смартфон Apple iphon",
      price: "7 300 000 сум ",
      price2: "от 2 435 000 сум ",
      gift: false,
      discount: false,
      trade: true,
      id: 10,
    },
  ],
};
export default cardData;
